"""Write generated files to disk."""

import logging
import shutil
from pathlib import Path
from typing import TYPE_CHECKING, List

from gimle.hugin.tools.tool import ToolResponse

if TYPE_CHECKING:
    from gimle.hugin.interaction.stack import Stack

logger = logging.getLogger(__name__)


def write_agent_files(
    stack: "Stack",
    output_path: str,
    agent_name: str = "",
) -> ToolResponse:
    """Write all generated files to the output directory.

    Args:
        stack: Agent stack (auto-injected)
        output_path: Directory where agent files should be written
        agent_name: Optional name of the agent (for README)

    Returns:
        ToolResponse with list of written files
    """
    env_vars = stack.agent.environment.env_vars
    generated_files = env_vars.get("generated_files", {})
    user_input = env_vars.get("user_input", {})

    # Use provided agent_name or fall back to env_vars
    if not agent_name:
        agent_name = user_input.get("agent_name", "agent")

    if not generated_files:
        return ToolResponse(
            is_error=True,
            content={"error": "No files have been generated yet"},
        )

    if not output_path:
        return ToolResponse(
            is_error=True,
            content={"error": "No output path specified"},
        )

    output_dir = Path(output_path)
    written_files: List[str] = []

    try:
        # Clean up previous agent files in the output directory
        if output_dir.exists():
            shutil.rmtree(output_dir)

        # Create output directory
        output_dir.mkdir(parents=True, exist_ok=True)

        # Create __init__.py for the agent package
        init_file = output_dir / "__init__.py"
        init_content = f'"""Generated Hugin agent: {agent_name}."""\n'
        init_file.write_text(init_content)
        written_files.append(str(init_file))

        # Create tools __init__.py
        tools_dir = output_dir / "tools"
        tools_dir.mkdir(exist_ok=True)
        tools_init = tools_dir / "__init__.py"
        tools_init.write_text('"""Agent tools."""\n')
        written_files.append(str(tools_init))

        # Write all generated files
        for file_path, content in generated_files.items():
            full_path = output_dir / file_path
            full_path.parent.mkdir(parents=True, exist_ok=True)
            full_path.write_text(content)
            written_files.append(str(full_path))

        # Create README.md
        description = user_input.get("description", "A Hugin agent")
        readme_content = f"""# {agent_name}

{description}

## Running the Agent

```bash
uv run run-agent --task main --task-path {output_path}
```

## Structure

- `configs/` - Agent configuration
- `tasks/` - Task definitions
- `templates/` - System prompts
- `tools/` - Custom tools

Generated by Hugin Agent Builder.
"""
        readme_path = output_dir / "README.md"
        readme_path.write_text(readme_content)
        written_files.append(str(readme_path))

        # Register the new agent with the environment so it becomes
        # immediately available to list_agents and launch_agent
        environment = stack.agent.environment
        loaded_config_name = environment.load_agent_from_path(str(output_dir))
        if loaded_config_name:
            logger.info(
                f"Registered new agent '{loaded_config_name}' in environment"
            )

        return ToolResponse(
            is_error=False,
            content={
                "output_path": str(output_dir),
                "files_written": written_files,
                "file_count": len(written_files),
                "message": f"Successfully created agent at {output_dir}",
                "registered_config": loaded_config_name,
            },
        )

    except Exception as e:
        return ToolResponse(
            is_error=True,
            content={
                "error": str(e),
                "partial_files": written_files,
            },
        )
